### ISSUE TITLE
Magnetic pogo pins

### ISSUE THREAD

**Issue by jmsether** [KRALYN/PositronV3#1]
![image](https://user-images.githubusercontent.com/5393103/169626946-9cb854a4-56bb-41c2-bac4-054210e2f03e.png)
I am having a hard time locating the magnetic pogo pins from the BOM I spent about 2 hours searching aliexpress with little to no luck. I am also having a hard time figuring out what the other two parts that are missing are. Are you able to provide any insight into this?

**Comment by KRALYN** [comment]
it is the magnetic connector 6pin; I think it is on line 21 in the current
revision. Also, are you sure you are going to order everything before I
upload the build series and instructions?

**Comment by KRALYN** [comment]
Also, DO NOT SMT Solder the connector! De select them. You are going to
solder wires to the pads.

**Comment by KRALYN** [comment]
I made BOM more clear in this regard.

**Comment by jmsether** [comment]
When you say connector, are you talking about U7? And I was planning on getting the board made and things milled and cut from the file. I can handle some of the milling and all the 3d printing.
