### ISSUE TITLE
ZIP is not ideal in git repositories

### ISSUE THREAD

**Issue by ascheucher** [KRALYN/PositronV3#11]
Hi KRALYN!

That's an awesome project! I am really tempted to rebuild the printer, but let's see whether I find time for that.

Just something I noticed, during checking your repo: ZIP files are not encouraged in git repositories.
You will lose the possibility to track changes and also AFAIK, git compresses everything anyway on transfer and storage.
It's just only drawbacks checking in zipped files.

Thanks for sharing your project!

**Comment by ascheucher** [comment]
Never used git lfs, but this sounds like the proper way to do it.

**Comment by luminous-flux** [comment]
It works well for CAD - it just tells git to treat the files as pure binary
blobs so it doesnt try to diff them as text with previous versions.

**Comment by KRALYN** [comment]
I think this application of Zip is fine since it is an CAD assembly.
