### ISSUE TITLE
Specifications

### ISSUE THREAD

**Issue by antordey51** [KRALYN/PositronV3#13]
| BEDHEATERFILM1 | Kapton Film Heater 200mm 100W | Bed heating 

For this part- the first link is of robotdigg & there's 6 options to choose from :
PL2020-12V
PL2121-12V
PL2525-12V
PL2020-24V
PL2121-24V
PL2525-24V

Please specify which one should we get. I cross checked with price to find a match but all options cost the same 12 USD & you haven't specified the voltage.

**Comment by KRALYN** [comment]
Hello, it is 24V, 100W heater, so it should be PL2020-24V. I’ll add this
spec in.
