### ISSUE TITLE
Materials Specifications

### ISSUE THREAD

**Issue by antordey51** [KRALYN/PositronV3#14]
For printing the Acrylic Panel Parts & as well  Custom metal parts - which technology should be used?
•CNC Machining 
•Sheet Metal
Also which material should be used?
•Aluminium 5083/5754/6082
•Steel S235JR/St52/S355
•Stainless Steel V2A/V4A

Or Everything can be printed in industrial/commercial plastics? If it can be done using plastics instead of Aluminium/Steel- that would really be cost saving.

Your input would really be helpful for whoever doing this project without any experience, Thanks.

**Comment by KRALYN** [comment]
I designed and simulated everything with their respective materials. For the manufacturing method; I think any method that satisfies the geometry and according to the engineering drawings would be sufficient. I think 6000 series Aluminum should work, the 5000 series Aluminum might be a bit weak. I real testing would needed to be done inorder to ensure the functions of the alternative materials.
