### ISSUE TITLE
Copper heater strips

### ISSUE THREAD

**Issue by antordey51** [KRALYN/PositronV3#16]
HEATERSTRIP1

Row 28 : Copper heater stripsFrost Fighter | Pick One

TOO EXPENSIVE Right now (89 dolars?)

Well, Whilst making the list- you had possibly found the price is 89 USD. The link(https://frostfighter.com/clear-view-order-guide.htm?add-to-cart=1366&v=402f03a963ba) you've added to the sheet- directly adds the item to cart and it shows $149 as of now.

So, Could you please revisit and confirm if this the same item with increased price or attach the actual product link- otherwise there's a chance others who can afford this may buy the wrong one which might not be useful:(

**Comment by KRALYN** [comment]
The idea is that eventually that there would be a film heater that users just stick on and not bother with the strips. The Frostfighter strips are only for prototyping.
