### ISSUE TITLE
Found the 1030 on AliExpress

### ISSUE THREAD

**Issue by 18Markus1984** [KRALYN/PositronV3#17]
![grafik](https://user-images.githubusercontent.com/52409213/174066492-889ab20b-612f-4d6a-8132-94feefe40608.png)

I found the 1030 extrusion on [AliExpress ](https://de.aliexpress.com/item/1005001957312144.html?spm=a2g0o.order_list.0.0.21ef5c5fu1CdhL&gatewayAdapt=glo2deu) maybe you can add the link to the BOM. The size values are at some points a little different, but shouldn't be bothering the build.
![grafik](https://user-images.githubusercontent.com/52409213/174067143-244a179f-c584-45e4-93ce-5b3f79419b44.png)
![grafik](https://user-images.githubusercontent.com/52409213/174067400-fd69a928-b481-4f3b-b2c6-581686bc332c.png)

**Comment by KRALYN** [comment]
Very nice! I think this piece will work as well. I'll add it into the BOM

**Comment by antordey51** [comment]
@18Markus1984 isn't the one from misumi cheap around 3 USD? I checked the Aliexpress link and for 250mm- it's around 9 USD:(

**Comment by 18Markus1984** [comment]
> @18Markus1984 isn't the one from misumi cheap around 3 USD? I checked the Aliexpress link and for 250mm- it's around 9 USD:(

Yes but not shippeable to Europe
