### ISSUE TITLE
What is the Hotend Heater block? Can't find it on BOM.

### ISSUE THREAD

**Issue by Owen12121212121** [KRALYN/PositronV3#21]

**Comment by FramingApp** [comment]
It has to be manufactured yourself or purchased through a supplier once they become available in the future. Watch the video here: [Hotend Segment of PostronV3 video](https://youtu.be/X_QLxTVtyng?t=1329)
If you want to get hold of a manufactured hotend ASAP, get in touch with @slicingblade on discord. He might be able to sort you out as he is manufacturing and selling kits himself.

**Comment by KRALYN** [comment]
I created Machined Parts-from Stocks section in BOM and all machined part names are listed within.
