### ISSUE TITLE
Unclear positions in BOM -> 3D printed parts

### ISSUE THREAD

**Issue by cyberhuman** [KRALYN/PositronV3#6]
Hi. Thank you very much for your project!

I started to source the parts required and noticed a couple of things in the 3D printed parts section:

1. It says "15mm pDia Synchromesh", but I think it's named `Small Synchrmesh Idler.stl` in the repository.
2. There is "M4 spacer 4.1mmx6" x 1. Does "x6" stand for 6 copies of this part?

**Comment by KRALYN** [comment]
I see, I’ll fix this soon. Thank you!

**Comment by KRALYN** [comment]
Fixed
